chore(main.go): import the "gin-hybrid/service" package in the "cmd/article/main.go" file to fix the undefined reference to "NewArticleService" error chore(main.go): import the "gin-hybrid/service" package in the "cmd/user/main.go" file to fix the undefined reference to "NewUserService" error chore(go.mod): update dependencies for "github.com/go-resty/resty/v2" and "go.etcd.io/etcd/api/v3" to their latest versions
fix(go.sum): remove unused golang.org/x/crypto v0.3.0 module
fix(go.sum): remove unused golang.org/x/net v0.4.0 module
fix(go.sum): remove unused golang.org/x/sys v0.3.0 module
fix(rest.go): return error message with service name when no available service
fix(reverse_proxy.go): send 503 error response when unable to parse endpoint URL
fix(router.go): add enableWebRouters flag to Setup function to conditionally register web routers

feat(article.go): add ArticleService struct and methods for handling article-related operations
feat(user.go): add UserService struct and methods for handling user-related operations